### ISSUE TITLE
pandas timeseries

### ISSUE THREAD

**Issue by peterdudfield** [SheffieldSolar/sp2ts#1]
Hi, Thanks for doing this. 

Would be great to add a way to do this from two pandas columns?

Thanks

**Comment by peterdudfield** [comment]
Ive done it like this for the moment 
```demand_df.apply(lambda x: sp2ts(date_=pd.Timestamp(x.settlementDate), sp_=int(x.settlementPeriod)), axis=1)```

**Comment by JamieTaylor-TUOS** [comment]
@peterdudfield this is pretty much the code snippet I use in downstream applications - I'm loathe to complicate the sp2ts package to work with non-built-in datetime types (np.datetime64, pd.Timestamp) - to my mind this would add complexity and make future updates harder (since we would have to support future changes to the NumPy and Pandas types/interfaces.
